{{ if or .Values.applications.istio.enabled (eq .Values.network.type "istio") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: {{ .Values.applications.argocd.namespace }}
  # todo: annotations
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.istio.base.namespace }}
  project: {{ .Values.project.name }}
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: {{ .Values.applications.istio.revision }}
    helm:
      valueFiles:
        {{ include "app-of-apps.valuesFilesIstioBase" . | nindent 16 }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
