{{ if .Values.applications.knative.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: {{ .Values.applications.knative.serving.namespace }}
  # todo: annotations
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.argocd.namespace }}
  project: {{ .Values.project.name }}
  source:
    path: templates/kustomizations/knative-serving/{{ .Values.project.platform }}-{{ .Values.project.environment }}-{{ .Values.project.profile }}
    kustomize:
      namespace: {{ .Values.applications.knative.serving.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
