{{ if and (or .Values.applications.istio.enabled (eq .Values.network.mode "istio")) .Values.applications.minio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: minio-virtual-service
  namespace: {{ .Values.applications.minio.namespace }}
  # todo: annotations
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
spec:
  hosts:
    - minio.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
  gateways:
    - {{ .Values.applications.istio.gateway.namespace }}/minio-ingress-gateway
  http:
    - route:
        - destination:
            host: minio-console.minio.svc.cluster.local
            port:
              number: 9001
{{ end }}
